# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-frontend-service
spec:
  selector:
    app: expense-tracker-frontend
  ports:
    - protocol: TCP
      port: 80 # External service port
      targetPort: 3000 # Port on the frontend pods
      nodePort: 30001 # A port on your Kubernetes node. Choose one between 30000-32767.
  type: NodePort # Exposes the service on a port on each node's IP