# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-backend-service
spec:
  selector:
    app: expense-tracker-backend
  ports:
    - protocol: TCP
      port: 8080 # Port on the service
      targetPort: 8080 # Port on the backend pods
  type: ClusterIP # Internal service, accessible only within the cluster